### ISSUE TITLE
So ,where can I download these three files?

### ISSUE THREAD

**Issue by Gpwner** [huiyegit/APLC_XLNet#2]
`12/21/2020 12:39:36 - INFO - pytorch_transformers.tokenization_utils -   Didn't find file ../models/added_tokens.json. We won't load it.
12/21/2020 12:39:36 - INFO - pytorch_transformers.tokenization_utils -   Didn't find file ../models/special_tokens_map.json. We won't load it.
12/21/2020 12:39:36 - INFO - pytorch_transformers.tokenization_utils -   Didn't find file ../models/spiece.model. We won't load it.`

**Comment by Gpwner** [comment]
where can i download your tokenizer files?

**Comment by huiyegit** [comment]
The source code needs to access the internet, then it will download the required files from AmazonAWS automatically.

![Selection_006](https://user-images.githubusercontent.com/31486250/102819536-a01d4300-43a1-11eb-8661-a76ce0ac810f.png)

**Comment by Gpwner** [comment]
Thank you for your reply, but for some reason I have to download these files manually.After I downloaded the files, there was another problem running the code：


```
the number of params:  119884032
12/22/2020 04:12:01 - INFO - __main__ -   Training/evaluation parameters Namespace(adam_epsilon=1e-08, adaptive_cutoff=[1978], cache_dir='', config_name='', data_dir='../data/EURLex', device=device(type='cuda'), div_value=2.0, do_eval=True, do_lower_case=False, do_train=True, eval_all_checkpoints=True, evaluate_during_training=False, fp16=False, fp16_opt_level='O1', gpu='0', gradient_accumulation_steps=1, last_hidden_size=768, learning_rate_a=0.002, learning_rate_h=0.0001, learning_rate_x=5e-05, local_rank=-1, logging_steps=500, max_grad_norm=1.0, max_seq_length=512, max_steps=-1, model_name_or_path='../models', model_type='xlnet', n_gpu=1, no_cuda=False, num_label=2, num_labels=3956, num_train_epochs=8.0, output_dir='../data/EURLex/tmp', output_mode='classification', overwrite_cache=False, overwrite_output_dir=True, per_gpu_eval_batch_size=12, per_gpu_train_batch_size=6, pos_label=24, save_steps=500, seed=42, server_ip='', server_port='', task_name='eurlex', tokenizer_name='', warmup_steps=0, weight_decay=0.0)
12/22/2020 04:12:01 - INFO - __main__ -   Loading features from cached file ../data/EURLex/cached_train_models_512_eurlex
Traceback (most recent call last):
  File "/home/xzc/pycharm-community-2020.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/xzc/pycharm-community-2020.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/xzc/project/APLC_XLNet/code/main.py", line 547, in <module>
    main()
  File "/home/xzc/project/APLC_XLNet/code/main.py", line 498, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "/home/xzc/project/APLC_XLNet/code/main.py", line 97, in train
    {'params': [p for n, p in model.module.transformer.named_parameters() if not any(nd in n for nd in no_decay)], 'weight_decay': args.weight_decay, "lr": args.learning_rate_x},
  File "/home/xzc/anaconda3/envs/MTC/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'XLNetForMultiLabelSequenceClassification' object has no attribute 'module'

Process finished with exit code 1
```




Can  you help me ?

**Comment by huiyegit** [comment]
You may need to spend some time debugging the source code. One potential reason may be the GPUs required in the config file.
![_20201221214144](https://user-images.githubusercontent.com/31486250/102842774-c361e580-43d5-11eb-8585-ae9407d44489.jpg)

**Comment by Gpwner** [comment]
I have only one GPU ,so I change the parameter --gpu to 0.But it is still not working.finally I figure it out by comment  line487 `elif args.n_gpu > 1:` in main.py:

```
    if args.local_rank != -1:
        model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.local_rank],                                                          output_device=args.local_rank,
                                                          find_unused_parameters=True)
    # elif args.n_gpu > 1:
    model = torch.nn.DataParallel(model)

    logger.info("Training/evaluation parameters %s", args)
```

Anyway thank you very much.
